export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_LIST_COMPLETE_REQUEST = 'ORDER_LIST_COMPLETE_REQUEST';
export const ORDER_LIST_COMPLETE_SUCCESS = 'ORDER_LIST_COMPLETE_SUCCESS';
export const ORDER_LIST_COMPLETE_FAIL = 'ORDER_LIST_COMPLETE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const UPDATE_STATUS_ORDER_ADMIN_REQUEST = 'UPDATE_STATUS_ORDER_ADMIN_REQUEST';
export const UPDATE_STATUS_ORDER_ADMIN_SUCCESS = 'UPDATE_STATUS_ORDER_ADMIN_SUCCESS';
export const UPDATE_STATUS_ORDER_ADMIN_FAIL = 'UPDATE_STATUS_ORDER_ADMIN_FAIL';
export const UPDATE_STATUS_ORDER_ADMIN_RESET = 'UPDATE_STATUS_ORDER_ADMIN_RESET';
