export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_ADDRESS_MY_REQUEST = 'ORDER_ADDRESS_MY_REQUEST';
export const ORDER_ADDRESS_MY_SUCCESS = 'ORDER_ADDRESS_MY_SUCCESS';
export const ORDER_ADDRESS_MY_FAIL = 'ORDER_ADDRESS_MY_FAIL';
export const ORDER_ADDRESS_MY_RESET = 'ORDER_ADDRESS_MY_RESET';

export const ORDER_LIST_ALL_REQUEST = 'ORDER_LIST_ALL_REQUEST';
export const ORDER_LIST_ALL_SUCCESS = 'ORDER_LIST_ALL_SUCCESS';
export const ORDER_LIST_ALL_FAIL = 'ORDER_LIST_ALL_FAIL';

export const ORDER_RETURN_AMOUNT_PRODUCT_REQUEST = 'ORDER_  RETURN_AMOUNT_PRODUCT_REQUEST';
export const ORDER_RETURN_AMOUNT_PRODUCT_SUCCESS = 'ORDER_  RETURN_AMOUNT_PRODUCT_SUCCESS';
export const ORDER_RETURN_AMOUNT_PRODUCT_FAIL = 'ORDER_ RETURN_AMOUNT_PRODUCT_FAIL';
export const ORDER_RETURN_AMOUNT_PRODUCT_RESET = 'ORDER_RETURN_AMOUNT_PRODUCT_RESET';

export const ORDER_PAYPAL_PAID_REQUEST = 'ORDER_PAYPAL_PAID_REQUEST';
export const ORDER_PAYPAL_PAID_SUCCESS = 'ORDER_PAYPAL_PAID_SUCCESS';
export const ORDER_PAYPAL_PAID_FAIL = 'ORDER_PAYPAL_PAID_FAIL';

export const ORDER_PAYPAL_PAID_CONFIRM_REQUEST = 'ORDER_PAYPAL_PAID_CONFIRM_REQUEST';
export const ORDER_PAYPAL_PAID_CONFIRM_SUCCESS = 'ORDER_PAYPAL_PAID_CONFIRM_SUCCESS';
export const ORDER_PAYPAL_PAID_CONFIRM_FAIL = 'ORDER_PAYPAL_PAID_CONFIRM_FAIL';

export const CALCULATE_FEE_SHIP_REQUEST = 'CALCULATE_FEE_SHIP_REQUEST';
export const CALCULATE_FEE_SHIP_SUCCESS = 'CALCULATE_FEE_SHIP_SUCCESS';
export const CALCULATE_FEE_SHIP_FAIL = 'CALCULATE_FEE_SHIP_FAIL';

export const GET_LABEL_ORDER_GHTK_REQUEST = 'GET_LABEL_ORDER_GHTK_REQUEST';
export const GET_LABEL_ORDER_GHTK_SUCCESS = 'GET_LABEL_ORDER_GHTK_SUCCESS';
export const GET_LABEL_ORDER_GHTK_FAIL = 'GET_LABEL_ORDER_GHTK_FAIL';

export const UPDATE_STATUS_ORDER_USER_REQUEST = 'UPDATE_STATUS_ORDER_USER_REQUEST';
export const UPDATE_STATUS_ORDER_USER_SUCCESS = 'UPDATE_STATUS_ORDER_USER_SUCCESS';
export const UPDATE_STATUS_ORDER_USER_FAIL = 'UPDATE_STATUS_ORDER_USER_FAIL';
export const UPDATE_STATUS_ORDER_USER_RESET = 'UPDATE_STATUS_ORDER_USER_RESET';

export const USER_REQUEST_CONFIRM_PAID_REQUEST = 'USER_REQUEST_CONFIRM_PAID_REQUEST';
export const USER_REQUEST_CONFIRM_PAID_SUCCESS = 'USER_REQUEST_CONFIRM_PAID_SUCCESS';
export const USER_REQUEST_CONFIRM_PAID_FAIL = 'USER_REQUEST_CONFIRM_PAID_FAIL';
export const USER_REQUEST_CONFIRM_PAID_RESET = 'USER_REQUEST_CONFIRM_PAID_RESET';
