export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

export const CREACTE_USER_REQUEST = 'CREACTE_USER_REQUEST';
export const CREACTE_USER_SUCCESS = 'CREACTE_USER_SUCCESS';
export const CREACTE_USER_FAIL = 'CREACTE_USER_FAIL';
export const CREACTE_USER_RESET = 'CREACTE_USER_RESET';

export const PROVINCE_REQUEST = 'PROVINCE_REQUEST';
export const PROVINCE_SUCCESS = 'PROVINCE_SUCCESS';
export const PROVINCE_FAIL = 'PROVINCE_FAIL';

export const AVATAR_REQUEST = 'AVATAR_REQUEST';
export const AVATAR_SUCCESS = 'AVATAR_SUCCESS';
export const AVATAR_FAIL = 'AVATAR_FAIL';

export const FORGOT_PASS_WORD_REQUEST = 'FORGOT_PASS_WORD_REQUEST';
export const FORGOT_PASS_WORD_SUCCESS = 'FORGOT_PASS_WORD_SUCCESS';
export const FORGOT_PASS_WORD_FAIL = 'FORGOT_PASS_WORD_FAIL';

export const VERIFY_RESET_PASS_WORD_REQUEST = 'VERIFY_RESET_PASS_WORD_REQUEST';
export const VERIFY_RESET_PASS_WORD_SUCCESS = 'VERIFY_RESET_PASS_WORD_SUCCESS';
export const VERIFY_RESET_PASS_WORD_FAIL = 'VERIFY_RESET_PASS_WORD_FAIL';

export const RESET_PASS_WORD_REQUEST = 'RESET_PASS_WORD_REQUEST';
export const RESET_PASS_WORD_SUCCESS = 'RESET_PASS_WORD_SUCCESS';
export const RESET_PASS_WORD_FAIL = 'RESET_PASS_WORD_FAIL';
